# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-24 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180624_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
