# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-24 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180624_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_path',
            field=models.ImageField(default='/home/sheshant/PycharmProjects/rest_api_for_users/images/xrSh9Z0.jpg', upload_to='images/'),
        ),
    ]
