# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180624_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlog',
            name='action_data',
            field=models.TextField(default=''),
        ),
    ]
